version: '3'
services:
  database:
    extends:
      file: ../common/docker-compose.yml
      service: database
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234567"
      POSTGRES_DB: "customers_dev"
  configserver:
    extends:
      file: ../common/docker-compose.yml
      service: configserver
  customerservice:
    image: marinasavchenko/onlinestore-customersrv:v1
    ports:
      - "8080:8080"
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"