version: '1'
services:
  configserver:
    image:  marinasavchenko/onlinestore-configsrv:v1
    ports:
      - "8888:8888"
    environment:
#      ENCRYPT_KEY:       "IMSYMMETRIC"
  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234567"
      POSTGRES_DB:       "customers_local"
  licensingservice:
    image: marinasavchenko/onlinestore-customersrv:v1
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
#      ENCRYPT_KEY:       "IMSYMMETRIC"