version: '3.3'
services:
  configserver:
    image:  marinasavchenko/onlinestore-configsrv:v1
    ports:
      - "8888:8888"
    environment:
      ENCRYPT_KEY: "STTEELCAROECJ"
  database:
    image:  postgres:9.5
    volumes:
      - pg_database:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234567"
      POSTGRES_DB: "customers_local"
      POSTGRES_PORT: "5432"
  customerservice:
    image:  marinasavchenko/onlinestore-customersrv:v1
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT: "8888"
      POSTGRES_DB: "customers_local"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234567"
      POSTGRES_HOST: "database"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY: "STTEELCAROECJ"
    links:
      - configserver
      - database
volumes:
  pg_database:
    external: true