version: '3'
services:
  configserver:
    image:  marinasavchenko/onlinestore-configsrv:v1
    ports:
      - "8888:8888"
  database:
    image:  postgres:11
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234567"
      POSTGRES_DB: "customers_local"
    links:
      - configserver: configserver
  customerservice:
    image:  marinasavchenko/onlinestore-customersrv:v1
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT: "8888"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234567"
      POSTGRES_DB: "customers_local"
      POSTGRES_HOST: "database"
      DATABASESERVER_PORT: "5432"
    links:
      - configserver: configserver
      - database: database
volumes:
  db: